### ISSUE TITLE
[Feat] Sign In With Apple (애플 로그인) 초기 구현 작업.

### ISSUE THREAD

**Issue by 220v-K** [DeveloperAcademy-POSTECH/MacC-Team15-GearCo#1]
### 📝 작업할 내용 요약

애플 로그인을 구현합니다. SIWA!

---

### 🛠️ Tasks

* [ ] 로그인 초기 화면 구현
* [x] 애플 로그인 버튼 구현 및 데이터 처리
* [x] Firebase Auth 연동
