### ISSUE TITLE
[Feat] 디자인 시스템 적용 - Color, Text 및 Image

### ISSUE THREAD

**Issue by earlysummer0303** [DeveloperAcademy-POSTECH/MacC-Team15-GearCo#24]
### 📝 작업할 내용 요약

컬러, 텍스트 및 이미지 익스텐션으로 하이파이에서 정해진 디자인 시스템 적용하겠습니당

### 🛠️ Tasks

* [x] Color+ Extension 작업
* [x] Text+ Extension 작업
* [ ] Image+ Extension 작업

### 참고 이미지
<!-- <img src="이미지주소.png" width="200" height="400"/> >>
<!-- <img src="이미지주소.png" width="40%"/> >>

**Comment by earlysummer0303** [comment]
추후 작업 순서 
- 버튼 시스템 정비
- 마이페이지

**Comment by earlysummer0303** [comment]
텍스트랑 컬러시스템 먼저 PR 하겠습니당
