### ISSUE TITLE
[Feat] 이유식 일괄 설정 뷰 틀작업

### ISSUE THREAD

**Issue by vanism2091** [DeveloperAcademy-POSTECH/MacC-Team15-GearCo#31]
### 📝 작업할 내용 요약

- [ ] 이유식 일괄 설정 뷰 틀 작업하기
---

### 🛠️ Tasks

* [ ] 이유식 일괄 설정 뷰 틀 작업
* [ ] custom segment picker 작업 완료하기

### 참고 이미지
<!-- <img src="이미지주소.png" width="200" height="400"/> >>
<!-- <img src="이미지주소.png" width="40%"/> >>
<img width="352" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-GearCo/assets/107124308/1fcb2dd2-3a5c-418b-8000-9d4e57441b1c">
