### ISSUE TITLE
[Feat] 재료 데이터 파일 추가 및 가공 작업

### ISSUE THREAD

**Issue by 220v-K** [DeveloperAcademy-POSTECH/MacC-Team15-GearCo#51]
### 📝 작업할 내용 요약

구글 SpreadSheet에 작업했던 재료 데이터 파일을 JSON 형식으로 변환을 완료하였고,
이 파일을 프로젝트 내에 넣어 Ingredient struct 형식으로 가공하여 사용할 수 있도록 하는 작업을 진행합니다.

---

### 🛠️ Tasks

* [ ] 재료 데이터 JSON 파일 추가
* [ ] JSON 형식에서 원하는 struct 형식으로 가공
* [ ] 가공한 데이터를 앱 전역에서 사용할 수 있도록, 앱 시작 시 불러오고 뿌려주기
