### ISSUE TITLE
[Feat] AddIngredientView 실제 재료 데이터 적용 및 DB 연결 준비 이것저것

### ISSUE THREAD

**Issue by 220v-K** [DeveloperAcademy-POSTECH/MacC-Team15-GearCo#53]
### 📝 작업할 내용 요약

AddIngredientView 측 실 데이터 연결 작업을 시작합니다.

---

### 🛠️ Tasks

* [ ] AddTestIngredientView / AddNormalIngredientView 분리
* [ ] 실제 재료 데이터로 띄워보기 시작
* [ ] 플랜 입력 뷰와 연계하여 DB에 올리는 틀 잡기
* [ ] DB의 plan 데이터 불러와 이것저것 분기처리(아이콘) 시작
