### ISSUE TITLE
[Feat] 월간 플래닝 뷰 실제 플래닝 데이터 DB fetch, 띄우기 / 빈 날짜 플랜 추가 기능 연결

### ISSUE THREAD

**Issue by 220v-K** [DeveloperAcademy-POSTECH/MacC-Team15-GearCo#63]
### 📝 작업할 내용 요약

월간 플래닝 뷰의 데이터를 실제 데이터로 변경하고, 플랜 추가 등 상호작용을 추가합니다.

---

### 🛠️ Tasks

* [x] 모든 플래닝 데이터를 DB에서 Fetch해오는 작업
* [x] 월간 플래닝 뷰에 알맞게 띄워주기
* [ ] 빈 날짜를 눌렀을 때 플랜 추가 기능

---

* [ ] 이미 계획이 있는 날짜를 눌렀을 때 하루 식단 상세 화면으로
* [ ] 그리고 계획 수정
=> 은 다음 PR로 분리하겠습니다.

**Comment by vanism2091** [comment]
good go get'em
