### ISSUE TITLE
[Feat] PlanListView와 파이어베이스 연결하기

### ISSUE THREAD

**Issue by vanism2091** [DeveloperAcademy-POSTECH/MacC-Team15-GearCo#68]
### 📝 작업할 내용 요약

---

### 🛠️ Tasks

* [x] PlanListView와 파이어베이스 연결하기
* [x] 연결 후 화면 잘 뜨는지 확인
* [x] 데이터 구조 변경이 필요하면 대응

### 참고 이미지
<!-- <img src="이미지주소.png" width="200" height="400"/> >>
<!-- <img src="이미지주소.png" width="40%"/> >>
