### ISSUE TITLE
[Feat] Meal Detail View 관련 할일들

### ISSUE THREAD

**Issue by vanism2091** [DeveloperAcademy-POSTECH/MacC-Team15-GearCo#70]
### 🛠️ Tasks

* [x] ingredient 삭제 구현
* [x] Meal Detail View - Ingredient chip에서 재료 타입에 따라 오른쪽 칩이 바뀌게
* [x] 업뎃 시 meal plans 에도 업데이트
