### ISSUE TITLE
[Feat] 월간 계획 화면 데이터 연결 2

### ISSUE THREAD

**Issue by 220v-K** [DeveloperAcademy-POSTECH/MacC-Team15-GearCo#78]
### 📝 작업할 내용 요약

#63 에서 분리한 다음 PR 작업 사항을 여기서.
#72 

---

### 🛠️ Tasks

* [x] 빈 날짜를 눌렀을 때 플랜 추가 기능
* [x] 이미 계획이 있는 날짜를 눌렀을 때 하루 식단 상세 화면으로
* [ ] 그리고 계획 수정
