### ISSUE TITLE
[Feat] AddTestIngredient 각종 추가 작업 - 2

### ISSUE THREAD

**Issue by 220v-K** [DeveloperAcademy-POSTECH/MacC-Team15-GearCo#83]
### 📝 작업할 내용 요약

재료 추가 화면 측에서 아직 작업하지 않은 세부 사항들을 작업합니다.

---

### 🛠️ Tasks

* [ ] 검색 기능 구현
* [x] 하단 버튼 fixed 처리 및 토스트메시지 구현
* [x] 새로운 재료 / 사용한 적 없는 재료에 따라 리스트에 뜨는 재료가 다르도록 변경
  * [x] 뷰 appear 시 재료 사용 횟수 카운팅 (임시)
  * [x] 자주 사용한 재료 구분
>   * [ ] IngredientUseCount 함수 작성
>   * [ ] save / delete 시 IngredientUseCount 업데이트

* [ ] 검색 버튼 옆 재료 구분 버튼 -> 스크롤 수정
* [x] 재료 리포트 기능 구현
