### ISSUE TITLE
[Feat] 리드 온리

### ISSUE THREAD

**Issue by vanism2091** [DeveloperAcademy-POSTECH/MacC-Team15-GearCo#95]
### 🛠️ Tasks
- [ ] Read-only 작업하기
  - [x] Plan List View
  - [ ] Monthly Planning
  - [ ] Plan Group Detai lView
  - [ ] Daily Plan List View
  - [ ] Meal Detail View

- [ ] 현재 이전은 read only만 된다면, change month도 달라져야 할 것 같다 :) - 기록이 없으면 disable?

### 참고 이미지
<!-- <img src="이미지주소.png" width="200" height="400"/> >>
<!-- <img src="이미지주소.png" width="40%"/> >>
